<a href="https://colab.research.google.com/github/chaitusomu25/NASSCOM/blob/main/NumPy_Practice_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Practice Exercises

Solve each question in the code cell below it. Do not just re-run the lab examples — use **different numbers/data** than what was shown in class so you are actually writing the logic yourself.

Run each cell with **Shift + Enter** and check that your output makes sense before moving to the next question.

### Q1. Creating a 1-D array
Create a 1-D NumPy array containing 6 numbers of your choice. Print the array and print its type using `type()`.

In [ ]:
import numpy as np
arr = np.array((12, 25, 15, 11, 30, 17))
print(arr)
print(arr.dtype)


[12 25 15 11 30 17]
int64


### Q2. Creating a 2-D array
Create a 2-D NumPy array with 3 rows and 2 columns (any numbers). Print the array.

In [ ]:
# Write your code here
import numpy as np
arr1 = np.array(((12, 25),(22, 19),(84, 109)))
print(arr1)

[[ 12  25]
 [ 22  19]
 [ 84 109]]


### Q3. Creating a 3-D array
Create a 3-D NumPy array made up of two 2x3 matrices (2 blocks, each with 2 rows and 3 columns). Print the array.

In [ ]:
import numpy as np
arr2 = np.array((((12, 25, 84),(109, 11, 25)),((100, 108, 92), (67, 12, 36))))
print(arr2)


[[[ 12  25  84]
  [109  11  25]]

 [[100 108  92]
  [ 67  12  36]]]


### Q4. Checking the number of dimensions
Using the three arrays you created in Q1, Q2, and Q3, print the number of dimensions of each using the `.ndim` attribute.

In [ ]:
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)


1
2
3


### Q5. Accessing elements with indexing
Create a 2-D array with 2 rows and 5 columns of your own numbers.
1. Print the 3rd element of the 1st row using positive indexing.
2. Print the last element of the 2nd row using **negative** indexing.

In [ ]:
arr3 = np.array(((10, 20, 30, 40, 50),(15, 25, 35, 45, 55)))
print(arr3[0, 2])


30


### Q6. Accessing elements in a 3-D array
Using the 3-D array you created in Q3, access and print one specific element using three indices, e.g. `arr[block, row, col]`.

In [ ]:
print(arr2[1, 1, 2])

36


### Q7. Checking data type
Create one NumPy array of integers and one NumPy array that contains at least one decimal number. Print the `.dtype` of each and explain in a comment why they are different.

In [ ]:
arr4 = np.array((10, 25, 20, 12, 16, 6, 17))
arr5 = np.array((84.0, 36.0, 44, 52, 79))
print(arr4.dtype)
print(arr5.dtype)


int64
float64


### Q8. Copy vs View
Create a 1-D array. Make a **copy** of it using `.copy()` and a **view** of it using `.view()`. Change the first element of the original array, then print the original array, the copy, and the view. In a comment, explain what you observe and why.

In [ ]:
arr6 = np.array([10,25,12,11,30,6,19,17])
newarr1 = arr6.copy()
newarr2 = arr6.view()
arr6 = ([15,25,12,11,30,6,19,17])
print(arr6)
print(newarr1)
print(newarr2)


[15, 25, 12, 11, 30, 6, 19, 17]
[10 25 12 11 30  6 19 17]
[10 25 12 11 30  6 19 17]


### Q9. Shape of an array
1. Create a 2-D array with 3 rows and 4 columns and print its `.shape`.
2. Create a 1-D array of 4 numbers with `ndmin=5` and print both the array and its shape.

In [ ]:
arr7 = np.array([[1,2,4,6],[84,109,25,12],[17,6,11,30]])
print(arr7.shape)
arr8 = np.array([[[[[84,25,109,12]]]]])
arr7
arr8
print(arr8.shape)


(3, 4)
(1, 1, 1, 1, 4)


### Q10. Reshaping arrays
Create a 1-D array with 15 elements. Reshape it into a 2-D array with 3 rows and 5 columns using `.reshape()`. Print the result.

In [ ]:
arr9 = np.array([84,109,143,25,12,11,5,26,24,19,22,30,6,17,7])
newarr3 = arr9.reshape(3,5)
newarr3


array([[ 84, 109, 143,  25,  12],
       [ 11,   5,  26,  24,  19],
       [ 22,  30,   6,  17,   7]])

### Q11. Linear algebra with NumPy
Solve the following system of equations using `np.linalg.solve()`:

2x + y = 11

x + 3y = 18

Print the values of x and y.

In [ ]:
a = np.array(((2,1),(1,3)))
b = np.array(((11),(18)))
x = np.linalg.solve(a,b)
print(x)


[3. 5.]


### Q12. arange, zeros, and ones
1. Use `np.zeros()` to create a 4x2 array of zeros.
2. Use `np.ones()` to create a 3x3 array of ones.
3. Use `np.arange()` to create an array of numbers from 5 to 30 with a step of 5.

Print all three.

In [ ]:
ar = np.zeros((4,2))
ar1 = np.ones((3,3))
ar2 = np.arange(5, 30, 5)
print(ar)
print(ar1)
print(ar2)


[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 5 10 15 20 25]


### Q13. Why NumPy is faster than plain Python
Create two Python lists of 500,000 numbers each. Time how long it takes to add them element-by-element using a Python loop (or list comprehension). Then convert both lists to NumPy arrays and time how long it takes to add them using `+`. Print both times and, in a comment, state which was faster and roughly by how much.

In [ ]:
import time
n = 500000
p = list(range(n))
q = list(range(n))
start = time.time()
r = [p[i] + q[i] for i in range(n)]
print('Python loop time:', round(time.time() - start, 4), 'seconds')
arr_a = np.array(p)
arr_b = np.array(q)
start = time.time()
result_array = arr_a + arr_b
print('NumPy vectorized time:', round(time.time() - start, 4), 'seconds')

Python loop time: 0.0662 seconds
NumPy vectorized time: 0.0028 seconds


### Q14. Vectors vs matrices
Create a 1-D NumPy array representing a single customer's features: `[height_cm, weight_kg, age]` (make up your own values). Then create a 2-D NumPy array representing 4 different customers with the same 3 features each. Print the `.shape` and `.ndim` of both arrays.

In [ ]:
c1 = np.array([5.4,45,19])
costumers = np.array([[6,58,19],[5.6,52,19],[5.6,40,19]])
print(c1.shape,c1.ndim)
print(costumers.shape,costumers.ndim)


(3,) 1
(3, 3) 2


### Q15. Indexing and slicing to build X and y
Create a 2-D array with 6 rows and 3 columns, where the last column is a target label (0 or 1) and the first two columns are features (make up your own numbers).
1. Print the first 3 rows only.
2. Print only the first column, for all rows.
3. Split the array into `X` (all columns except the last) and `y` (only the last column), and print both.

In [ ]:
import numpy as np
ch = np.array([[1,2,3],[2,4,6],[3,6,9],[4,8,12],[5,10,15],[6,12,18]])
print(ch[2])
for i in range(0,5):
    print(ch[i][0])
c1 = ch[:,:-1]
c2 = ch[:, -1]
print(c1)
print(c2)


[3 6 9]
1
2
3
4
5
[[ 1  2]
 [ 2  4]
 [ 3  6]
 [ 4  8]
 [ 5 10]
 [ 6 12]]
[ 3  6  9 12 15 18]


### Q16. Vectorized operations and boolean masking
Create a 1-D NumPy array of 8 exam scores (0-100) of your choice. Without using any loop:
1. Add 5 bonus marks to every score and print the result.
2. Print a boolean array showing which scores are 50 or above.
3. Print only the scores that are 50 or above using boolean masking.

In [42]:
marks = np.array((99,98,99,98,100,100,97,99))
print(marks+5)
print(marks>50)
print(marks[marks>30])


[104 103 104 103 105 105 102 104]
[ True  True  True  True  True  True  True  True]
[ 99  98  99  98 100 100  97  99]
